/* ── Role keyword maps ── */
const ROLE_KEYWORDS = {
  "Frontend Developer": [
    "javascript",
    "typescript",
    "react",
    "vue",
    "angular",
    "html",
    "css",
    "tailwind",
    "redux",
    "next.js",
    "webpack",
    "responsive design",
    "rest api",
    "accessibility",
    "figma",
  ],
  "Backend Developer": [
    "node.js",
    "express",
    "java",
    "spring",
    "python",
    "django",
    "flask",
    "rest api",
    "graphql",
    "sql",
    "postgresql",
    "mongodb",
    "redis",
    "docker",
    "microservices",
    "authentication",
  ],
  "Full Stack Developer": [
    "javascript",
    "react",
    "node.js",
    "express",
    "html",
    "css",
    "sql",
    "mongodb",
    "rest api",
    "git",
    "authentication",
    "docker",
    "responsive design",
    "redux",
    "typescript",
  ],
  SDE: [
    "data structures",
    "algorithms",
    "system design",
    "object oriented programming",
    "git",
    "testing",
    "ci/cd",
    "cloud",
    "aws",
    "docker",
    "kubernetes",
    "sql",
    "problem solving",
  ],
  "Data Analyst": [
    "sql",
    "excel",
    "python",
    "power bi",
    "tableau",
    "data visualization",
    "statistics",
    "pandas",
    "numpy",
    "etl",
    "data cleaning",
    "a/b testing",
    "dashboards",
  ],
  Other: [
    "communication",
    "problem solving",
    "teamwork",
    "git",
    "sql",
    "microsoft office",
    "leadership",
  ],
};

/* ── Skill category keyword lists ── */
const SKILL_CATEGORY_KEYWORDS = {
  languages: [
    "javascript",
    "typescript",
    "python",
    "java",
    "c++",
    "c#",
    "golang",
    "ruby",
    "php",
    "kotlin",
    "swift",
    "scala",
    "dart",
    "rust",
    "r",
    "bash",
    "sql",
  ],
  frameworks: [
    "react",
    "angular",
    "vue",
    "node.js",
    "express",
    "django",
    "flask",
    "spring",
    "next.js",
    "nestjs",
    "tailwind",
    "bootstrap",
    ".net",
    "laravel",
    "fastapi",
    "redux",
    "svelte",
    "nuxt",
  ],
  databases: [
    "mongodb",
    "mysql",
    "postgresql",
    "sqlite",
    "redis",
    "firebase",
    "oracle",
    "dynamodb",
    "cassandra",
    "supabase",
    "mariadb",
  ],
  cloudDevops: [
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "jenkins",
    "git",
    "github actions",
    "ci/cd",
    "terraform",
    "linux",
    "nginx",
    "ansible",
  ],
  tools: [
    "figma",
    "postman",
    "jira",
    "vs code",
    "webpack",
    "vite",
    "npm",
    "yarn",
    "excel",
    "power bi",
    "tableau",
    "notion",
    "slack",
    "trello",
  ],
};

/* ── Soft skills to detect in raw text ── */
const SOFT_SKILLS = [
  "leadership",
  "teamwork",
  "communication",
  "collaboration",
  "problem solving",
  "problem-solving",
  "time management",
  "adaptability",
  "ownership",
  "mentoring",
  "public speaking",
  "critical thinking",
  "creativity",
  "conflict resolution",
  "decision making",
  "initiative",
];

module.exports = {
  ROLE_KEYWORDS,
  SKILL_CATEGORY_KEYWORDS,
  SOFT_SKILLS,
};
